[2024-06-04T13:17:54.644+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_sla_viz.sleep_sla scheduled__2024-05-14T00:10:00+00:00 [queued]>
[2024-06-04T13:17:54.724+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_sla_viz.sleep_sla scheduled__2024-05-14T00:10:00+00:00 [queued]>
[2024-06-04T13:17:54.725+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-06-04T13:17:54.741+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): sleep_sla> on 2024-05-14 00:10:00+00:00
[2024-06-04T13:17:54.820+0000] {standard_task_runner.py:60} INFO - Started process 201 to run task
[2024-06-04T13:17:54.826+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_sla_viz', 'sleep_sla', 'scheduled__2024-05-14T00:10:00+00:00', '--job-id', '742', '--raw', '--subdir', 'DAGS_FOLDER/dag_sla_visualization.py', '--cfg-path', '/tmp/tmp0d6vceq8']
[2024-06-04T13:17:54.829+0000] {standard_task_runner.py:88} INFO - Job 742: Subtask sleep_sla
[2024-06-04T13:17:55.220+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_sla_viz.sleep_sla scheduled__2024-05-14T00:10:00+00:00 [running]> on host b4b0ed2599ea
[2024-06-04T13:17:55.633+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_sla_viz' AIRFLOW_CTX_TASK_ID='sleep_sla' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-14T00:10:00+00:00'
[2024-06-04T13:17:55.635+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_sla_visualization.py", line 9, in task_sleep_sla
    time.sleep(20)
NameError: name 'time' is not defined
[2024-06-04T13:17:55.725+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_sla_viz, task_id=sleep_sla, execution_date=20240514T001000, start_date=20240604T131754, end_date=20240604T131755
[2024-06-04T13:17:55.826+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 742 for task sleep_sla (name 'time' is not defined; 201)
[2024-06-04T13:17:55.935+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-04T13:17:56.119+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
